In [3]:
import tensorflow as tf

string_var = tf.Variable("This is a string", tf.string)
number_var = tf.Variable(64, tf.int16)
float_var = tf.Variable(3.67, tf.float64)

In [9]:
rank1_tensor = tf.Variable(["test", "ok", "diego", "arturo"], tf.string) 
rank2_tensor = tf.Variable([["test", "ok"],["test", "yes"]], tf.string)

In [10]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [4]:
tensor_demo_1 = tf.ones([1,2,3])
tensor_demo_2 = tf.reshape(tensor_demo_1, [2,3,1])
tensor_demo_3 = tf.reshape(tensor_demo_2, [3, -1])

In [13]:
rank2_tensor.shape

TensorShape([2, 2])

In [6]:
print(tensor_demo_1)
print(tensor_demo_2)
print(tensor_demo_3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
